EXTENSION_TO_MARKDOWN = {
    ".py": "python",
    ".js": "javascript",
    ".html": "html",
    ".css": "css",
    ".java": "java",
    ".c": "c",
    ".cpp": "cpp",
    ".cs": "csharp",
    ".php": "php",
    ".rb": "ruby",
    ".go": "go",
    ".swift": "swift",
    ".ts": "typescript",
    ".rs": "rust",
    ".kt": "kotlin",
    ".m": "objective-c",  # or "matlab" based on context
    ".r": "r",
    ".pl": "perl",
    ".lua": "lua",
    ".groovy": "groovy",
    ".scala": "scala",
    ".f": "fortran",
    ".f90": "fortran",
    ".hs": "haskell",
    ".ml": "ocaml",
    ".erl": "erlang",
    ".sh": "shell",
    ".bash": "bash",
    ".zsh": "zsh",
    ".sql": "sql",
    ".ps1": "powershell",
    ".dart": "dart",
    ".elm": "elm",
    ".purs": "purescript",
    ".clj": "clojure",
    ".cljs": "clojurescript",
    ".rkt": "racket",
    ".vb": "vbnet",       # for VB.NET; classic VB might be different
    ".vbs": "vbscript",
    ".asm": "assembly",
    ".s": "assembly",
    ".pas": "pascal",
    ".prg": "foxpro",
    ".cob": "cobol",
    ".julia": "julia",
    ".matlab": "matlab",
    ".prolog": "prolog",
    ".ada": "ada"
}

